### ISSUE TITLE
there is a error that "No module named 'spekpy'" after "npm run serve"

### ISSUE THREAD

**Issue by dreamwatchman** [WebxCT/WebCT#58]
![image](https://user-images.githubusercontent.com/56901464/229701810-cfd55ff0-8eb8-47e8-8fd5-5c444d71ba21.png)

**Comment by WYVERN2742** [comment]
It looks like your environment failed to install correctly, did you use the [environment.yml](https://github.com/WebxCT/WebCT/blob/master/environment.yml) with conda/mamba?

An easy fix is to install spekpy with `pip install git+https://bitbucket.org/spekpy/spekpy_release.git`

Let me know if this helps, I'm currently working on a bundled distributable to make WebCT easy for end-users to run.

**Comment by dreamwatchman** [comment]
Thanks very much for your help, it works by install packages in environnment.yml file.It is owesome, if thers is a a bundled distributable.

**Comment by WYVERN2742** [comment]
Lovely! If you ever [get the chance to post in discussions](https://github.com/WebxCT/WebCT/discussions) about your thoughts on WebCT (what was bad, what was good, etc) that'd be great and help make this tool better!
